server:
   port: 8083
spring:
   application:
      name: kafka-consumer
   kafka:
      bootstrap-servers: localhost:9092  # Dirección de tu Kafka
    # Alternative Kafka configuration, same as KafkaConsumerConfig
    #  consumer:
    #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #     value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    #     properties:
    #        schema:
    #           registry:
    #              url: "http://127.0.0.1:8081"  
    #        specific:
    #           avro:
    #              reader: "false" 
    #     group-id: my-group  
